/*
Warm up

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

// var
//
// y = (y%2==0){ sum +=y; }

// var i;
// var y = (i%2==0)
//
// for(i=1;i<=4000000; i++){
// }
// { sum +=y; }
//         console.log(y);

var sum = 0;
for (var i=0; i < 10; i++) {
    sum += 10[i];
}
console.log(sum);
